### PR TITLE
Ignore attributes when they contain arrays

### PR DESCRIPTION
**Pull request by thyseus**
This is an small workaround to avoid this error when using arrays as attribute values (which should be serialized somehow before saving and unserialized in afterFind()):

image

We should consider supporting this case properly in an future yii2-audit version.

### CODE REVIEW

**Comment by Blizzke** [comment]
There might be an issue regarding array'ed values, but your patch effectively stops anything from being logged at all.. Both will always be arrays as they contain a list of attributes and their values.

**Comment by thyseus** [comment]
Oh dammit. I will rework this, thanks for being that attentive.

**Comment by thyseus** [comment]
@Blizzke what do you think about this approach? https://github.com/bedezign/yii2-audit/pull/188/commits/31c7e704f47e01b7cce3546f246a65d2cc90d7e0

**Comment by thyseus** [comment]
@Blizzke Just a kind reminder that this issue is still open. I am using the great yii2-audit module in an project and would dislike to do an own fork just because of this small change. Thanks a lot :)

**Comment by cornernote** [comment]
He seems to be afk for a while.

Please change your solution to Json::encode if it's an array.

Apart from that it looks good, happy to pull it in.

**Comment by thyseus** [comment]
@cornernote any progress with this issue? any chance to get this into the next release? thanks

**Comment by cornernote** [comment]
I can't seem to see a link to a pull request. Let me know what it is and
ill have a look

**Pull request merged**
