### PR TITLE
Bugfixes for the earlier optimisation (#217)

### PR DESCRIPTION
**Pull request by shalvah**
Noticed a few bugs on re-checking the code in my earlier PR (#217). Fixed them now.

- array_walk doesn't always modify array keys in place
- date()'s second parameter typically works with a timestamp

Sorry for the bother, @Blizzke and co. I really should stop sleep-deprived coding :confused:

### CODE REVIEW

**Comment by Blizzke** [comment]
I'll see if I can draft a new release today, pretty important that those panels work :)

For the near future I was thinking -  seeing that we have this same piece of code in all the views - we might move it to a trait as a function and add it to the models or something. What do you think @cornernote ?

**Comment by shalvah** [comment]
That would be a good idea. Kept wondering if there was a better way while copying and pasting the code across these files @Blizzke. But, for the time being, can you help merge this PR? I don't want to be responsible for people opening new issues :blush:

**Comment by Blizzke** [comment]
That it was going to get merged was never in doubt :) Was just wondering in general.

**Comment by shalvah** [comment]
thanks :slightly_smiling_face:

**Pull request merged**
