### PR TITLE
add an option to disable most common timestamp fields

### PR DESCRIPTION
**Pull request by thyseus**
add an option to disable most common timestamp fields (active by default)

### CODE REVIEW

**Comment by Blizzke** [comment]
I love that you are doing pull requests to add good functionality, but would you mind also adding tests? We try to keep the coverage as high as possible.

**Comment by thyseus** [comment]
Is there an document on how to get the test environment running locally? Currently travis shows a lot of problems, with the last 4 failing tests concerning my PR: 

https://travis-ci.org/bedezign/yii2-audit/jobs/196511195

**Comment by cornernote** [comment]
Something upstream in the test process changed and we are currently having
a lot of failed tests as a result.  Haven't had time to look into it.

**Comment by thyseus** [comment]
@cornernote any news with this? would do unit tests when travis is working again (and if i get the test suite running at my local dev machine)

**Comment by cornernote** [comment]
Travis tests are all working now

**Comment by thyseus** [comment]
I´m stuck :-( https://github.com/bedezign/yii2-audit/issues/203

**Pull request merged**
