### PR TITLE
date create fix

### PR DESCRIPTION
**Pull request by schmunk42**
Please double-check it, but this should be the "nicer" implementation for https://github.com/bedezign/yii2-audit/commit/e4ac37d3ed712516557bbb96b0e7f7340dc396ff

### CODE REVIEW

**Comment by shalvah** [comment]
It's actually nicer, but I think https://github.com/bedezign/yii2-audit/pull/219/commits/f60f1c44006a90a09d9130d5722162877cc44eed removes the need for that expression even

**Comment by schmunk42** [comment]
In which branch is f60f1c4? I can't see it on master.

Could you tag a new version, 1.0.12 is unusable on PHP 7.2 without e4ac37d or this PR.

**Comment by cornernote** [comment]
@schmunk42 is this still an issue, or has a new version since been tagged?

Are you able to do a new PR with this nicer change so that it merges easily?

**Comment by schmunk42** [comment]
None of the fixes linked above is in a release, only on master.
I don't think I'll find time soon to review and update this, it should also be reviewed with the current changes since they are on master already.

**Comment by Blizzke** [comment]
Going to close this as it's been open for ages.

**Pull request closed without merging**
