### PR TITLE
fix php 7.2 compatibility

### PR DESCRIPTION
**Pull request by StalkAlex**

### CODE REVIEW

**Comment by Blizzke** [comment]
Thanks for the PR. 

As a reference, this is for #231 ([@ Yii2](https://github.com/yiisoft/yii2/issues/7936))

We will have to update the composer files too, since BaseObject was only added in 2.0.13
Currently the constraint is ">= 2"
Would you be so kind as to update those as well? "^2.0.13" should suffice I think.

**Comment by StalkAlex** [comment]
> As a reference, this is for #231 (@ Yii2)

Yes, that's right.

> Currently the constraint is ">= 2"

But now version of yii is "2.*", not sure If I understand you correctly.

**Comment by Blizzke** [comment]
If anyone with (for example) Yii 2.0.12 installs this, it will let them, but it will fail because `BaseObject` doesn't exist yet in that version.
The files need to get "^2.0.13" (`>= 2.0.13 <3`)instead of "2.*" (`>=2.0.0`)

**Comment by StalkAlex** [comment]
Ok, I get it, done.

**Comment by karataserkan** [comment]
Then we can not use yii2-audit when yii `< 2.0.13` ?

**Comment by Blizzke** [comment]
That would be the consequence indeed. Alternative would be to let it as is. Yii >= 2.0.13 implements a dummy `Object` class that gets loaded when your php < 7.2
The consequence of leaving it as is will be that it cannot be used by people on PHP 7.2... It's a bit of a conundrum

**Comment by StalkAlex** [comment]
This is where you raise middle number in version and new version become 1.1 as @balrok proposed.

**Comment by Blizzke** [comment]
Doing that was a necessity already since the mailparser extension was required so we'll probably go that path.
I'll look into doing a new release one of the next days and will merge this then.

**Comment by Blizzke** [comment]
Because of the changes I did to get the 1.0.13 release ready first so that people not willing to upgrade to Yii 2.0.13 yet can finally use a stable version, this PR now has some conflicts. It.s just easier to just manually port it into the new version so I'll be closing this. Expect a 1.1 release shortly.

**Pull request closed without merging**
