### PR TITLE
Viewer

### PR DESCRIPTION
**Pull request by MGHollander**
I've added a viewer, screenshots and some little documentation. Finally I changed the actions and views to the Yii2 default.

### CODE REVIEW

**Comment by Blizzke** [comment]
@MGHollander: Very nice job. Thank you for that!

**Comment by MGHollander** [comment]
I forgot to remove the announcement about the missing viewer from the readme

**Comment by Blizzke** [comment]
I'll remove it, about to add a commit anyway.
Now that you've added the viewer I think access control should be in place. 
I am tempted to rename the controller to DefaultController btw, so that you can just browse to /auditing/ instead. What do you think?

**Comment by MGHollander** [comment]
I totally agree. 

I'm also thinking about adding the yii2-audit-trail. Do you prefer to add it in your package or should I create my own? (witch I already did to see how it all works since it's my first package and I was wondering how it's done)

**Comment by Blizzke** [comment]
I will make the modifications to the controller. 

The audit trail is related functionality so if you feel like it, by all means. 
Also feel free to add yourself as the composer.json etc if you like, after all you are a contributor now :)

I'm currently experimenting with logging errors from the frontend javascript as well but haven't figured out a generic method to accomplish it (yet). Currently it is very site specific so I haven't added it.

**Pull request merged**
