### PR TITLE
Refactor chart panel renderings 

### PR DESCRIPTION
**Pull request by shalvah**
In line with what @Blizzke suggested in https://github.com/bedezign/yii2-audit/pull/218, I've refactored the logic for retrieving the audit data shown on the homepage into a trait, which I included in the Default Controller and all panels using it. Also made a small bugfix to the logic, where items were being grouped by the datetime instead of the date

### CODE REVIEW

**Comment by Blizzke** [comment]
Looks nice, thanks a lot. 
I'm going to try to free up some time one of the next days to integrate this and release it

Note to self: Should really look into why the HHVM tests are failed with a class Db not found, sigh.

**Comment by shalvah** [comment]
Any update on when this can be merged?

**Comment by shalvah** [comment]
@Blizzke :eyes:

**Comment by shalvah** [comment]
@Blizzke @cornernote :eyes:

**Comment by shalvah** [comment]
Hey guys @Blizzke @cornernote sorry to bug, but this is still here...

**Comment by Blizzke** [comment]
Sorry for the delay.

**Pull request merged**
