### PR TITLE
added tracking for request/response headers and redirect url

### LINKED ISSUE #15: missing redirect from the request data
the yii1 module used to track the redirect url, do you know how to do that in yii2 ?

### PR DESCRIPTION
**Pull request by cornernote**
fixes #15

### CODE REVIEW

**Comment by cornernote** [comment]
The only problem with this is that is has write AuditEntry.data at the start and the end of the request.

I considered 2 solutions:
1) write all the data at the end of the request - however this may be bad incase the script dies and has no chance to write the data
2) use the `addData()` method to store request/response headers as extra data

Let me know your thoughts.

**Comment by Blizzke** [comment]
I've specifically added the data functionality to link "stuff" to the entries that not everyone will want. Imo the headers are one of those, so is the referrer etc. The `type` column was meant to be an indicator of what sort of data was in there, we can perfectly predefine a number of these for displaying (like http_headers and/or referrer). So my idea is to just use `addData()` with agreed upon `type`

**Comment by Blizzke** [comment]
Typo btw, I meant `redirect` not `referrer`... Still early here.

**Comment by cornernote** [comment]
To me the headers are a fundamental part of the request/response.  Even more important than `$_SERVER`.

In addition the `redirect` is as important than the `referrer`, and seems to belong with url/referrer, not in extra data.

I really don't want to modify each application I create to tell it to save this as extra data, it should be handled by the auditing automatically (even if it is optional).

I see extra data as things that are not part of every request.  For example if I want to track some random array that helps me debug a section of code.

**Comment by cornernote** [comment]
feel free to add me on skype if its easier to discuss some things - my username is `cornernote`

**Comment by Blizzke** [comment]
I think you are misunderstanding what I'm trying to say. 
I'm not saying I don't want the audit module being able to store the headers, I do. 
This can be very useful for people. I'm just saying that this is data that not everyone needs, hence the storing in the extra data table. 

If we define some sort of extra behavior that can link to either the begin or the end of the audit logging we can provide a bases for other possible data in the future

Something like: $extraData => ['headers', 'redirects'] that then would load and attach hose behaviors. Those would then be responsible for storing the things in the data table.

**Comment by cornernote** [comment]
I understand what you mean, but using the same logic I could say that not everyone wants `$_SERVER`.  Just because it's a superglobal, doesn't mean I want to store it with every `AuditEntry`.

Also, I prefer the way the data is laid out as opposed to the extra data.  Extra data is all bunched into one section whereas each element in data gets its own section.

**Comment by cornernote** [comment]
You didn't comment on this:
> `redirect` seems to belong with url/referrer, not in extra data.

**Comment by Blizzke** [comment]
Yes, you have a good point regarding `$_SERVER`  (and all the other ones). 
When I started this plugin I didn't really thing it would get so packed with features as where we seem to be heading. In that sense, perhaps it is nicer data-wise to move out the bigger pieces of data and put all of them separately in the extra data table. Users could then decide what the need enabled, without the module forcing them to store everything. Might not be where you were aiming at, but I kind of like that flexibility.

Since every data record linked to an audit entry also has a type, we can not only use this to create them via an extra behavior, we can also do this to predefine a number of data-views. Eg a _data_headers view for the headers etc. If there is no dedicated view found it would be shown as it is now, a blob of text. 
That should also tackle your concerns regarding layout?

Along that path of logic referrer is indeed better off in the actual entry table since it is nearly always relevant.

**Comment by cornernote** [comment]
Yes, I had the same issue in the yii1 module...  By the time you track all this info (non-optionally) it became an ass-load of data to retain.

I really like the idea of putting data into the extra data table.  It means you can cleanup selective chunks of data, for example remove all the `$_SERVER` data older than a month.

As I think more about it, I am inclined to want all the superglobal data to be stored as extra data.  Why try to serialize it into a field when there is a better structure in the database for it?!

Should I do a PR where all the superglobal data is stored as extra data, and then the module can be configured to make everything optional?

I still strongly feel that `redirect` should be stored in the `AuditEntry` along with  `url`, `referrer`, etc.  It seems this PR is really for 2 things, should I do the redirect as a new PR so that we can discuss it on its own?

**Comment by Blizzke** [comment]
That was my reasoning indeed. The more I think about it the more I like it. 
We'll still have to serialize the data of course, but it'll be split per global instead of combining them all.
(So a `$_SERVER`, `$_GET`, `$_POST`, ...) per entry.
Combining that with the behaviors to determine what to track and the views per type to display it and I think we should be golden.

I hindsight of our discussions so far I am inclined to agree with your statement regarding the redirect. So I guess we can keep it within a single PR. I would love to see input from @MGHollander on all this as well though, he spent considerate time on the module as well so far.

**Pull request closed without merging**
