### PR TITLE
fixed yii2-debug constraint

### PR DESCRIPTION
**Pull request by schmunk42**
The commit https://github.com/bedezign/yii2-audit/commit/18ae5035d443ffd7a56774cd8e1ad5feebb7a5eb introduced a dependency on a constant, add in `2.0.7` of yii2-debug, see https://github.com/yiisoft/yii2-debug/commit/ed07955e80185874d4d244e8e5c25cd8a890e82e

### CODE REVIEW

**Comment by cornernote** [comment]
Can't merge from my phone. Need to fix hvvm or wait until tomorrow when I can do it from desktop.

**Comment by schmunk42** [comment]
HHVM is not a real bug, but no worries - tomorrow is totally fine, just a new tag would be cool ;)

```
Worker information
hostname: i-02c4411-precise-production-2-worker-org-docker.travisci.net:d38606e8-d590-4d35-

[...]

Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
```

**Comment by cornernote** [comment]
Yeah I saw that, seems every month the test suit needs some change or tweak.

**Comment by schmunk42** [comment]
Yeah, that's one reason why I moved so much stuff to Docker.
But the matrix testing on Travis is still very powerful.

**Pull request merged**
