### PR TITLE
Add overRide variable to over ride the old and new value of related m…

### PR DESCRIPTION
**Pull request by Te7a-Houdini**
i had a case in our business logic , that we must show values instead of ids numbers in oldValue column & newValue column .

so in the behavior function we will add this variable and it's settings .

`'overRide' => [
                    'tag_id' => ['table_name' => 'tag' , 'search_field' => 'parent_id' , 'return_field' => 'name']
                ]`

so this will over ride the tag_id variable in oldValue and newValue columns before saving in the database in the audit_trail table.

kindly find the screen shots .

After Change
after change

Before Change
before change

Multiple Ids
multiple ids

### CODE REVIEW

**Comment by cornernote** [comment]
Nice suggestion, thanks for the PR.

Couple of small issues:

- override is one word, are you able to change overRide and OverRide to override and Override ?

- i think the method `getCommaString` isn't really needed, it can be written as follows (please test to make sure I am correct with this):

```
implode(', ', \yii\helpers\ArrayHelper::map($newOverRideValues, $queryParams['return_field'], $queryParams['return_field']))
```

If you can make these changes and give it a quick test then I'll be happy to accept this PR.

**Comment by cornernote** [comment]
One more thing, are you able to add some notes to the behavior documentation here?:

https://github.com/bedezign/yii2-audit/blob/gh-pages/docs/trail-panel.md

**Comment by cornernote** [comment]
Another one more thing...

I think the following should be camel case:

`table_name` to `tableName`
`search_ield` to `searchField`
`return_field` to `returnField`

**Comment by Te7a-Houdini** [comment]
i have made the changes and it works fine , you are right :+1: , the getCommaString function wasn't needed

**Pull request merged**
