### PR TITLE
Method signature of AuditEntry::getErrors should be same as yii\base\Model::getErrors

### PR DESCRIPTION
**Pull request by iamfrankhe**
Method signature of AuditEntry::getErrors should be same as Yii2 yii\base\Model::getErrors

### CODE REVIEW

**Comment by Blizzke** [comment]
I guess the method name is a tad unfortunate and we should probably change it now that I think about it, but getErrors actually has nothing to do with the underlying validation functionality.

**Comment by iamfrankhe** [comment]
Well, I just want to get rid of this warning:

PHP Strict Warning – yii\base\ErrorException

Declaration of bedezign\yii2\audit\models\AuditEntry::getErrors() should be compatible with yii\base\Model::getErrors($attribute = NULL)

**Comment by Blizzke** [comment]
Understood. 
I will rename the function so that it frees up the actual validation functionality again and gets rid of your warning.

**Comment by iamfrankhe** [comment]
Thanks

**Comment by raviteja1452** [comment]
Hello , Iam New to this, I ve just installed bedezign yii2 module, 
i am able to get the log tables filled, but not able to get the link to the view, 
Can some one please help

**Comment by raviteja1452** [comment]
http://localhost/path/to/index.php?r=auditing

I am not able to get what does path/to/ mean in this

**Comment by Blizzke** [comment]
Hallo, please don't use an issue or pull request to ask questions that have nothing to do with it. 
Create a new issue. 
As to your question... It's just your own website url but with the auditing route behind it via either ?r=auditing or /auditing if you have prettyUrls enabled.

**Comment by Blizzke** [comment]
@iamfrankhe done.

**Comment by iamfrankhe** [comment]
Thanks @Blizzke

**Pull request closed without merging**
